version: "3.4"
services:
  app:
      build: "./app"
      ports:
        - 8000:8000
      volumes:
        - ./app:/app
      environment:
        - SERVICE_ENVIRONMENT=local
      depends_on:
        - mongo
  mongo:
    image: "mongo:4.0"
